spring.application.name=greenhouse-web

spring.datasource.url=${GREENHOUSE_DB_URL:jdbc:mysql://localhost:3306/greenhouse?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
spring.datasource.username=${GREENHOUSE_DB_USERNAME:root}
spring.datasource.password=${GREENHOUSE_DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
